

@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzk3MDI1Mzh9.Bp2puqwjHOscDY3bMBlefMAOPH6vGVpb7oqUNsw2Upk
GET http://localhost:3000/walks
Authorization: Bearer {{jwt}}
###
GET http://localhost:3000/walks/7
Authorization: Bearer {{jwt}}
###
POST http://localhost:3000/walks
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "optimal_steps": 4900 ,
  "miles": 2.45 ,
  "status":true,
  "date": "11/09/2021"
}

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Mo Salah",
  "email": "mosalah@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "mosalah@gmail.com",
  "password": "password"
}