

@jwt = 
GET http://localhost:3000/walks

###
GET http://localhost:3000/walks/7

###
POST http://localhost:3000/walks
Content-Type: application/json
Authorization: Bearer {{jwt}}
{
  "optimal_steps": 4900 ,
  "miles": 2.45 ,
  "status":true,
  "date": "11/09/2021"
}

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "walker@gmail.com",
  "password": "password"
}